/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'customerPrincipal' : Principal,
  'address' : string,
  'timestamp' : bigint,
  'items' : Array<[Product, Quantity]>,
  'phoneNumber' : string,
  'totalPrice' : number,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type Quantity = bigint;
export type Update = [] | [string];
export interface _SERVICE {
  'addProductDirectly' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[ProductId, Quantity], undefined>,
  'createMultipleProducts' : ActorMethod<[Array<ProductInput>], undefined>,
  'createOrder' : ActorMethod<
    [string, string, Array<[Product, Quantity]>],
    undefined
  >,
  'createProduct' : ActorMethod<
    [string, string, number, string, string],
    ProductId
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCartContents' : ActorMethod<[], Array<[Product, Quantity]>>,
  'getNextProductId' : ActorMethod<[], ProductId>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'incrementNextProductId' : ActorMethod<[bigint], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, Update, Update, [] | [number], Update, Update],
    undefined
  >,
  'updateProductPrice' : ActorMethod<[ProductId, number], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];