/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Quantity = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'customerPrincipal' : IDL.Principal,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(IDL.Tuple(Product, Quantity)),
  'phoneNumber' : IDL.Text,
  'totalPrice' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([ProductId, Quantity], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(Product, Quantity))],
      [],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCartContents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Product, Quantity))],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'updateProductPrice' : IDL.Func([ProductId, IDL.Float64], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Quantity = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'customerPrincipal' : IDL.Principal,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(IDL.Tuple(Product, Quantity)),
    'phoneNumber' : IDL.Text,
    'totalPrice' : IDL.Float64,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([ProductId, Quantity], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(Product, Quantity))],
        [],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCartContents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Product, Quantity))],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'updateProductPrice' : IDL.Func([ProductId, IDL.Float64], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };